DROP TABLE IF EXISTS smooth-hub-460704-v8.liquor_sale_.Staging_Sales;
CREATE TABLE smooth-hub-460704-v8.liquor_sale_.Staging_Sales (
    invoice_line_no STRING,
    date STRING,
    store STRING,
    name STRING,
    address STRING,
    city STRING,
    zipcode STRING,
    store_location STRING,
    county_number STRING,
    county STRING,
    category STRING,
    category_name STRING,
    vendor_no STRING,
    vendor_name STRING,
    itemno STRING,
    im_desc STRING,
    pack STRING,
    bottle_volume_ml STRING,
    state_bottle_cost STRING,
    state_bottle_retail STRING,
    sale_bottles STRING,
    sale_dollars STRING,
    sale_liters STRING,
    sale_gallons STRING,
    file_name STRING NOT NULL,
    processed_timestamp DATETIME NOT NULL
);