DROP TABLE IF EXISTS Staging_Sales;
CREATE TABLE Staging_Sales (
    invoice_line_no TEXT,
    date TEXT,
    store TEXT,
    name TEXT,
    address TEXT,
    city TEXT,
    zipcode TEXT,
    store_location TEXT,
    county_number TEXT,
    county TEXT,
    category TEXT,
    category_name TEXT,
    vendor_no TEXT,
    vendor_name TEXT,
    itemno TEXT,
    im_desc TEXT,
    pack TEXT,
    bottle_volume_ml TEXT,
    state_bottle_cost TEXT,
    state_bottle_retail TEXT,
    sale_bottles TEXT,
    sale_dollars TEXT,
    sale_liters TEXT,
    sale_gallons TEXT,
    file_name TEXT NOT NULL,
    processed_timestamp DATETIME NOT NULL
);